### ISSUE TITLE
avoid publishing everything

### ISSUE THREAD

**Issue by 6a6d74** [wmo-cop/wis2node-metadata-mgmt#10]
Currently, the workflow publishes _everything_ that's a `.yml` in the `/metadata/mcf` folder. Actually, all these MCFs get processed. But the 2 half of the workflow cycles through all the `.json` files in the root of the `gh-pages` branch. This means every time you run the workflow, everything gets re-published. 

It would be good to only publish the (set of) metadata record(s) you're interested in.

**Comment by tomkralidis** [comment]
Perhaps we can constrain by directory?  Options:

1. establish a "draft" directory, and everyone in `metadata/mcf` that is NOT in `draft` get published?
2. establish a "for-publish" directory, which would be tired directly to the publishing trigger/workflow.  This essentially means that publishing metadata is a function of moving a file to a certain directory
3. other options?

I would lean towards option 2 which would only trigger publishing of new/updated metadata files in `metadata/mcf/for-publish`

Thoughts?

**Comment by tomkralidis** [comment]
Fixed using some git trickery (in the GitHub publish action) to determine which files were last changed.
