### ISSUE TITLE
github-action-failure-nothing-to-commit-working-tree-clean

### ISSUE THREAD

**Issue by 6a6d74** [wmo-cop/wis2node-metadata-mgmt#6]
When committing changes to gh-pages, the action fails because it thinks there's nothing to do. I've tried numerous times to force it by making changes to my .yml Metadata Control Files. But, in hindsight,  because you automatically build the .json files from the .yml files, I'd need to make substantive (i.e., non-whitespace) changes to the .yml to make the .json look different. So - the result is that the action sees no change on gh-pages and quits.

I tested this by making a "substantive change" to one of the .yml files; changed the hoursofservice by 15 minutes! This non-whitespace change was enough to create a change in the .json files on gh-pages and enable the action to complete.

Screenshot: 

![github-action-failure-nothing-to-commit-working-tree-clean](https://github.com/wmo-cop/wis2node-metadata-mgmt/assets/2519144/091d60b3-a1ba-4529-b4b7-5f481f84045a)

**Comment by tomkralidis** [comment]
@6a6d74 update pushed in https://github.com/wmo-cop/wis2node-metadata-mgmt/commit/ff478c44f2cb8cdef8f1f32d1508be4f90027e5c, let me know if this fixes things.
